# Generated by Django 5.0.3 on 2024-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
