# Generated by Django 5.0.3 on 2024-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_boat_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
