# Generated by Django 5.0.3 on 2024-03-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='products/'),
        ),
    ]
