# Generated by Django 5.0.3 on 2024-04-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_tour_created_at_tour_update_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
