# Generated by Django 5.0.3 on 2024-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_boat_remove_product_category_tour_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
