# Generated by Django 5.0.3 on 2024-04-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_boat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
