# Generated by Django 5.0.3 on 2024-04-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_tour_duration_tourimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourImages',
            new_name='TourImage',
        ),
    ]
