# Generated by Django 5.0.3 on 2024-04-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_tourimages_tourimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourimage',
            old_name='Image',
            new_name='image',
        ),
    ]
