# Generated by Django 5.0.3 on 2024-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
