# Generated by Django 5.0.3 on 2024-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_description_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_alt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
