# Generated by Django 5.0.3 on 2024-04-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_featured_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
