name: Deploy to EC2 and Reload Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Change the working directory
        run: cd /home/ubuntu/boatwale

      - name: Checking git status
        run: sudo git status

      - name: Pull the latest changes
        run: sudo git pull origin main

      - name: Checking the nginx syntax error
        run: sudo nginx -t

      - name: Reload nginx
        run: sudo systemctl reload nginx