name: Deploy to EC2 and Reload Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 via SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
      
      - name: SSH into EC2 and Run Commands
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Run multiple commands here
            cd /home/ubuntu/boatwale
            ls -l
            git status
            git pull
            sudo nginx -t
            sudo sytemctl reload nginx
          EOF