name: Deploy to EC2 and Reload Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /home/ubuntu/boatwale
            echo "Checking git changes"
            sudo git status
            echo "Pulling latest changes"
            sudo git pull
            echo "Checking nginx syntax errors"
            sudo nginx -t
            echo "Relaoding nginx"
            sudo systemctl reload nginx