name: Deploy to EC2 and Reload Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: SSH into EC2 and Run Commands
        run: |
          cd /home/boatwale/boatwale
          git status
          git pull
          sudo systemctl restart gunicorn.socket
          sudo nginx -t
          sudo systemctl reload nginx
